name: mapbox_gl_platform_interface
description: A common platform interface for the mapbox_gl plugin.
version: 0.15.0
homepage: https://github.com/Sipioteo/maps_3_0_0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

