const renamedIosProperties = {
  "iconImage": "iconImageName",
  "iconRotate": "iconRotation",
  "iconSize": "iconScale",
  "iconKeepUpright": "keepsIconUpright",
  "iconTranslate": "iconTranslation",
  "iconTranslateAnchor": "iconTranslationAnchor",
  "iconAllowOverlap": "iconAllowsOverlap",
  "iconIgnorePlacement": "iconIgnoresPlacement",
  "textTranslate": "textTranslation",
  "textTranslateAnchor": "textTranslationAnchor",
  "textIgnorePlacement": "textIgnoresPlacement",
  "textField": "text",
  "textFont": "textFontNames",
  "textSize": "textFontSize",
  "textMaxWidth": "maximumTextWidth",
  "textJustify": "textJustification",
  "textMaxAngle": "maximumTextAngle",
  "textWritingMode": "textWritingModes",
  "textRotate": "textRotation",
  "textKeepUpright": "keepsTextUpright",
  "textAllowOverlap": "textAllowsOverlap",
  "symbolAvoidEdges": "symbolAvoidsEdges",
  "circleTranslate": "circleTranslation",
  "circleTranslateAnchor": "circleTranslationAnchor",
  "circlePitchScale": "circleScaleAlignment",
  "lineTranslate": "lineTranslation",
  "lineTranslateAnchor": "lineTranslationAnchor",
  "lineDasharray": "lineDashPattern",
  "fillAntialias": "fillAntialiased",
  "fillTranslate": "fillTranslation",
  "fillTranslateAnchor": "fillTranslationAnchor",
  "rasterHueRotate": "rasterHueRotation",
  "rasterResampling": "rasterResamplingMode",
  "visibility": "isVisible",
  "rasterBrightnessMin": "minimumRasterBrightness",
  "rasterBrightnessMax": "maximumRasterBrightness",
};

const dartTypeMappingTable = {
  "string": "String",
  "array": "List",
  "number": "double",
  "enum": "String",
  "promoteId": "String",
  "boolean": "bool",
  "*": "Object"
};

const swiftTypeMappingTable = {
  "string": "String",
  "array": "Array",
  "number": "Double",
  "enum": "String",
  "promoteId": "String",
  "boolean": "Bool",
  "*": "Object"
};
